### ISSUE TITLE
Problem using the same composite conditional over two composite routes

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [NaluKit/nalu#100]
I'm having a problem using the same composite conditional over two controllers with different routes:

![imagen](https://user-images.githubusercontent.com/13700946/67291284-99ffae00-f4e1-11e9-888f-c4d940251279.png)

Nalu version: 1.3.2

**Comment by FrankHossfeld** [comment]
I hope, I have fixed that one. A new SNAPSHOT containing the fix is published: 1.3.5-SNAPSHOT.

Plaese can you test the fix and give a feedback. Thanks

**Comment by RaulPampliegaMayoral** [comment]
I will check ASAP. Thanks!

**Comment by RaulPampliegaMayoral** [comment]
@FrankHossfeld I have tested the fix and is working fine. When can you publish a realese from 1.3.5?

**Comment by FrankHossfeld** [comment]
Great ... I think, I will publish Nalu v2.0.0 & v1.3.5 at the weekend. Mybe I can publish before and update the docs later.  Is it urgent?

**Comment by RaulPampliegaMayoral** [comment]
No problem, is not urgent (when my manager see "snapshot" gets a little nervous...jajaja)

**Comment by FrankHossfeld** [comment]
got it ... :-)

Hope you will find some time to update to v2.0.0. Has a lot of nice features.

**Comment by FrankHossfeld** [comment]
Btw, I will close the issue now. (but we can use it for fther discussions)

Fixed
