### ISSUE TITLE
Add possibility to hide components of cached controllers instead of detach

### ISSUE THREAD

**Issue by TDesjardins** [NaluKit/nalu#114]
When navigating between different pages with cached controllers the DOM-content will attached on show and detached on hide which is fine for the most use cases. If the DOM-content (respectively the page) contains stateful content like an iframe or a video the state will be lost on reattach.
Therefore it would be useful to have the ability to configure cached controllers to show / hide DOM-content instead of attach / reattach (see https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/hidden).

**Comment by FrankHossfeld** [comment]
Well, that issue is getting really old.

@TDesjardins Should I keep this issue open?

One point, hiding components means, that someone can make them visible again by using the dev tools. That might lead to unwanted results.

**Comment by FrankHossfeld** [comment]
I'll close the issue due to no response. In case it gets relevant again, please reopen the issue or create a new one.
