### ISSUE TITLE
Declaration of collections of composites

### ISSUE THREAD

**Issue by elnicko** [NaluKit/nalu#121]
**Story**
As a developer of applications with many lists, I want to have the possibility to separate the code that declares, populates and renders the parent controller (list, table, tree, etc) from the code that declares, populates and renders the children/items in order to avoid multi-level and complex code in one single component/controller. Furthermore, the data provisioning of the items to be rendered needs to support asynchronous operations.

**Current state of affairs**
The composite approach seems the obvious suspect. However currently it cannot work with dynamic lists of data items. 

**Theoretical target**
Basically Nalu should be able to get a list of items to be rendered and a component/composite with which to render each individual item.

**Solution considerations**
Nalu needs to know:
- a name prefix (for accessing a single composite)
- the composite controller
- the selector where to add the composite
- the data object (for injecting a single data object into the composite) or better yet a facility for provision of said data.

**Implementation proposition 1**
Create a new annotation called ListComposite or CollectionComposite.
```
@ListComposite(
    name = "dtoComposite",
    compositeController = MyDtoComposite.class,
    selector = „slotForDto“,
    dataObject = MyDto.class)
```
Force the user to implement the data provisioning mechanism...
```
@Override
public void dataProvider(NaluCallback naluCallback) {
   List<MyDto> list = ... 
    naluCallback.callback(list) 
}
```

**Implementation proposition 2**
Add two parameters to the existing Composite annotation: collection and collectionProvider. Then follow the pattern of AbstractCompositeCondition and introduce a new base class for data provisioning called e.g. AbstractCollectionProvider.
```
Composites({ 
    @Composite(
        name = „dtoComposite",
        compositeController = DtoListItemComposite.class,
        selector = „slotForDtoListItems“,
        dataObject = MyDto.class,
        collection = true,
        collectionProvider = MyDtoListItemsProvider.class
    ) 
})
public class DtoListComposite
{
...
}

public class MyDtoListItemsProvider<List<MyDto>> extends AbstractCollectionProvider<AppContext>
{
    @Override
    public void loadComposite(Consumer<List<MyDto>> consumer)
    {
        // sync/async call to REST and consumer.accept on success
        // or obtain directly from context and accept...
    } 
}
```

**Comment by elnicko** [comment]
**Implementation proposition 3**
Based on *Implementation proposition 2* one could go a step further and lose the *collection = true* and *collectionProvider* parameters of the annotation. Instead, a more general parameter dataProvider can be introduced. Depending on the needs of the developer, the dataProvider can return a collection of transfer objects or a single transfer object (the example below shows a real world-life example of both being used in a single parent). 

This streamlines the pattern by removing the concern of whether the data is a collection or a single item or something entirely else. What and how data is provisioned is then a concern of the supplied data provider class and not of the composite itself or their parent anymore. That way the composites can be *fed* with data by the parent regardless of the data structure via the same Java API. And said Java API is very simple: it amounts only to the declaration of the provider itself. This keeps the different concerns at their right places and also allows for the design of completely context-free composites and thus their code can be reused much more flexibly, better tested etc.

The following example depicts the design of a complex list view containing:
* A list of items (DtoListItemComposite). This is our collection composite, where a new instance is created for each provided collection item.
* A panel containing summary of the list items, e.g. analytics, a chart, etc. (DtoSummaryComposite). This is our single item composite, where there is only one item provided and one instance created.
```
Composites({ 
    @Composite(
        name = „dtoSummaryComposite",
        compositeController = DtoSummaryComposite.class,
        selector = „summarySlot“,
        dataObject = MyDtoSimmary.class,
        dataProvider = MyDtoSummaryProvider.class
    ),
    @Composite(
        name = „dtoListItemsComposite",
        compositeController = DtoListItemComposite.class,
        selector = „listItemsSlot“,
        dataObject = MyDto.class,
        dataProvider = MyDtoListItemsProvider.class
    ) 
})
public class DtoListComposite
{
...
}

public class MyDtoSummaryProvider<MyDtoSimmary> extends AbstractDataProvider<AppContext>
{
    @Override
    public void loadComposite(Consumer<MyDtoSimmary> consumer)
    {
        // sync/async call to REST and consumer.accept on success
        // or obtain directly from context and accept...
    } 
}

public class MyDtoListItemsProvider<List<MyDto>> extends AbstractCollectionDataProvider<AppContext>
{
    @Override
    public void loadComposite(Consumer<List<MyDto>> consumer)
    {
        // sync/async call to REST and consumer.accept on success
        // or obtain directly from context and accept...
    } 
}
```

**Comment by FrankHossfeld** [comment]
@elnicko I will close the issue-Looks no one is interested in and I have no use case. 

If someone needs this feature, please reopen the issue!
