### ISSUE TITLE
Support routing in popup controller

### ISSUE THREAD

**Issue by masterdany88** [NaluKit/nalu#123]
Imagine case.
Open app, go to users page, which display table with users details. In this table you can sort, filter and select concrete user to edit. Now You can redirect to user edit page(which supports routing). You are gonna lose all table edits.  Other option is to display popup for edition. You won't lose all of this sorting and filtering You did. But pop up should be routable and bookmarkable so You can easily go back or share link.

Proposal for routing is:
`127.0.0.1/app/users` to display user page table. 
And for popup
`127.0.0.1/app/users?popup1=/app/users/2/edit`

There can be more cases, like you go to bank app. Go to history and search for last month payments, and then You need repeat them all. You can click to repeat one by one in new popup window without closing history view. And for example minimalise windows. 

Or you just work with Super Development Mode on popup edit form and you wonna refresh to see changes. 

Check domino ui windows below:
![image](https://user-images.githubusercontent.com/1161910/76704214-ae825400-66d7-11ea-88f9-e61cc5ddbdf2.png)
![image](https://user-images.githubusercontent.com/1161910/76704221-be019d00-66d7-11ea-899e-107ba20618fc.png)
They are persitant between pages(it is domino mvc). So it would very good to have them bookmarkable, f.e. If You open 2 window and wanna compare/ or copy between.
Unfortunatelly domino ui still miss minimalise, size change functionality, but this would be extra case. Check how new email window works in gmail.com
![image](https://user-images.githubusercontent.com/1161910/76704303-5861e080-66d8-11ea-8a6e-4f0952037c73.png)

There is many cases. But if We go for dedicated PopUpController, It should have rich functionality, then It won't different much from simple dialog window.
It will be good to have them routable and bookmarkable.

Also it would be good If We could open each view as a popup, f.e.: You open page with user list, and then clik window icon to move this content to modal window, that can be drag around, but I do not know how technically it would work.

**Comment by FrankHossfeld** [comment]
By definition, popups are not bound to routes.
