### ISSUE TITLE
Upgrade gwt 2.8.2 -> 2.9.0 and address dependency convergence

### ISSUE THREAD

**Issue by robinroos** [NaluKit/nalu#128]
GWT has released 2.9.0.

As well as upgrading to the new version, it is suggested to resolve any dependency convergence issues.

**Comment by robinroos** [comment]
After updating the pom to generate the Dependency Convergence report, but before changing the GWT version, the following dependencies are the subject of convergence issues:

```
com.google.auto:auto-common
com.google.code.gson:gson
com.google.guava:guava
com.google.truth:truth
commons-codec:commons-codec
xml-apis:xml-apis
```

**Comment by FrankHossfeld** [comment]
A simple upgrade of Nalu to GWT version 2.9.0 will break compatibility to older versions of GWT. GWT 2.9.0 is based on Elemental2 1.0.0 which is incompatible with Elemental2 1.0.0-rc1 from GWT 2.8.2.

**Comment by FrankHossfeld** [comment]
Nalu runs with GWT 2.9.0 now.
