### ISSUE TITLE
Provide other ways to create controllers and components

### ISSUE THREAD

**Issue by hpehl** [NaluKit/nalu#13]
Right now controllers, components, and composites have to have a public, zero-argument constructor. This works well with APT and code generation but limits the possible use cases. 

For instance, I'd like to use Elemento templates as components. This is currently not possible since Elemento templates don't have a public, zero-argument constructor. Instead, they have to be created using a static factory method (which returns the generated template class). 

As a workaround, I have two "views": 

1. the Nalu component which contains the bulk of the component code & logic and 
2. the Elemento HTML template as a dumb view which is created in the `render` method of the component. 

I use this technique in one of my projects. See the code in package [org.jboss.schlawiner.client.settings](https://github.com/hpehl/schlawiner/tree/master/frontend/src/main/java/org/jboss/schlawiner/client/settings) as an example.

If Nalu provided a way to customize the creation of the component, I could get rid of the extra "view" class.

**Comment by FrankHossfeld** [comment]
Yep, agree. 

Think, generating the code for a non zero argument constructor is quite easy. But, Nalu needs to know which are the parameters. At the moment, controllers are created by a ControllerFactory and the ControllerFactory has only access to the parameters in case it creates a controller. To solve this requirement, we have to tell Nalu where to get the values of the parameters for the non zero argument constructor. 

Any idea for an elegant solution?

**Comment by hpehl** [comment]
TBH no 😉

I think it's hard to find the right balance between the default use cases (public, zero-argument constructor) and the more advanced use cases. 

I need to think about it and will comment here, In case I get enlightened.

**Comment by FrankHossfeld** [comment]
Ok. If i got an idea, I will comment it here, so we can discuss it.

**Comment by FrankHossfeld** [comment]
Btw, can you provide an example how Elemento Templates are created?
Thanks

**Comment by hpehl** [comment]
Elemento templates are abstract classes which have a static factory method. This method returns the generated template implementation.

#### Elemento template

```java
@Templated
abstract class SettingsView implements IsElement<HTMLElement> {

    static SettingsView create() {
        return new Templated_SettingsView(); // return the generated implementation
    }
}
```

#### Nalu Component

```java
public class SettingsComponentImpl 
        extends AbstractComponent<SettingsController, HTMLElement> 
        implements SettingsComponent {

    @Override
    public void render() {
        initElement(SettingsView.create().asElement());
    }
}
```

**Comment by FrankHossfeld** [comment]
I think, creating a controller with a non zero argument constructor will be really hard to implement. In case of creating a component, it might be easier. In mvp4g2 it is possible to tell the framework that the view is created by the presenter. May be this solution might help to create a component inside the controller in Nalu.

First, we need an interface:
```
/**
 * Controllers marked with this interface will create the component instance.
 *
 * @param <V> type of the component
 * @param <W> type of the element
 */
public interface IsComponentCreator<V extends IsComposite<?> {
    V createComponent();
}
``` 
In case Nalu recognized a controller with this interface, Nalu will call createComponent() and set the return value into the component instead of creating an instance using the new command.

Inside a controller, there will be a method that looks like that:
```
public IMyComponent() {
    return SettingsView.create();
}
```
and the render method of the component class looks like that:
```
public void render() {
    initElement(this.asElement());
}
```

I am not really familiar with Elemento templates. Do you think, this might help to avoid the second component class?

**Comment by hpehl** [comment]
I think that should work. Is this wip or already available in Nalu?

**Comment by FrankHossfeld** [comment]
Implementation is done.

Using the `IsCompoentCreator`-interface with a controller, tells Nalu to call the `createComponent`-method. The method has to return  an instance of the component. Now, it is up to the controller to create the component instance.  

Some more informations: https://github.com/NaluKit/nalu/wiki/08.-Controller-&-Component#component-creation

Hope that helps.

**Comment by hpehl** [comment]
Thanks, @FrankHossfeld. I've tested the `IsComponentCreator` interface in my project and was able to delete the additional view class. Works like a charm!

IMO the issue can be resolved.

**Comment by FrankHossfeld** [comment]
Great to hear! Thanks for testing.
