### ISSUE TITLE
remove @Debug annotation

### ISSUE THREAD

**Issue by FrankHossfeld** [NaluKit/nalu#134]
Removing the @Debug annotation and the related code will reduce the size of the generated code.

Is the debug annotation a valuable feature or can we remove it?

**Comment by RaulPampliegaMayoral** [comment]
In my case it can be removed, I don't use it

**Comment by FrankHossfeld** [comment]
I think most of the Nalu users will not miss it.

**Comment by FrankHossfeld** [comment]
First tests show that the generated JS has an 8 to 16 % smaller size and the generated code looks much cleaner.

**Comment by masterdany88** [comment]
I've never used. I don't know its purpose. I use Nalu successfully it 2 production stage projects :D

**Comment by FrankHossfeld** [comment]
I have pushed an update (remove the debug stuff) to the feature branch:  https://github.com/NaluKit/nalu/tree/feature/134

**Comment by FrankHossfeld** [comment]
looks like no one is using the @Debug annotation. 

@Debug annotation will be removed with the next release!

**Comment by FrankHossfeld** [comment]
Done
