### ISSUE TITLE
Understanding of composite in sub module

### ISSUE THREAD

**Issue by mamta** [NaluKit/nalu#140]
Hi, 

I took https://github.com/NaluKit/nalu-examples/tree/master/NaluDominoLoginModuleApplication

I added a FooterComposite https://github.com/mamta/nalu-module-demo/blob/master/nalu-module-demo-login/src/main/java/com/mamta/nalu/loginapplication/module/login/client/ui/contnet/footer/FooterComposite.java

and used it in ListController, it works.

When I tried to use it in LoginController, I am getting a failure. Is it not allowed?

[INFO] Nalu-Processor finished ... processing takes: 668.5 ms

[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] No processor claimed any of these annotations: com.github.nalukit.nalu.client.component.annotation.Composites
[WARNING] File for type 'com.mamta.nalu.loginapplication.module.login.client.LoginModuleModuleImpl' created in the last round will not be subject to annotation processing.
[INFO] 2 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /D:/git/01_my_repos/nalu/nalu-module-demo/nalu-module-demo-login/target/generated-sources/annotations/com/mamta/nalu/loginapplication/module/login/client/LoginModuleModuleImpl.java:[91,14] constructor CompositeControllerReference in class com.github.nalukit.nalu.client.internal.CompositeControllerReference cannot be applied to given types;
  required: java.lang.String,java.lang.String,java.lang.String,java.lang.String,boolean
  found: java.lang.String,java.lang.String,java.lang.String,java.lang.String
  reason: actual and formal argument lists differ in length
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for NaluDominoLoginModuleApplication - Nalu Example Project 2.0.0-SNAPSHOT:
[INFO] 
[INFO] NaluDominoLoginModuleApplication - Nalu Example Project SUCCESS [  0.210 s]
[INFO] nalu-module-demo-shared ............................ SUCCESS [  1.816 s]
[INFO] nalu-module-demo-login ............................. FAILURE [  6.061 s]
[INFO] nalu-module-demo-client ............................ SKIPPED
[INFO] nalu-module-demo-server ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.456 s
[INFO] Finished at: 2020-09-11T09:28:46+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project nalu-module-demo-login: Compilation failure
[ERROR] /D:/git/01_my_repos/nalu/nalu-module-demo/nalu-module-demo-login/target/generated-sources/annotations/com/mamta/nalu/loginapplication/module/login/client/LoginModuleModuleImpl.java:[91,14] constructor CompositeControllerReference in class com.github.nalukit.nalu.client.internal.CompositeControllerReference cannot be applied to given types;
[ERROR]   required: java.lang.String,java.lang.String,java.lang.String,java.lang.String,boolean
[ERROR]   found: java.lang.String,java.lang.String,java.lang.String,java.lang.String
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :nalu-module-demo-login

Thanks

**Comment by FrankHossfeld** [comment]
can you please provide a small example that shows the problem?
Thanks!

**Comment by mamta** [comment]
https://github.com/mamta/nalu-module-demo

This is the example where I tried. It is a copy of your example. During compiling I am getting this failure.

**Comment by FrankHossfeld** [comment]
mmmh, looks like you found a bug. :)

**Comment by FrankHossfeld** [comment]
Please, switch the Nalu version to HEAD-SNAPSHOT and try again. Just deployed a new SNAPSHOT version containing the fix.

Keep in mind, that the Debug annotation is no longer supported. Just delete the code, if you have used it.

If you ran into problems, open another issue or ping me at Gitter.

**Comment by mamta** [comment]
It works, thanks 👍
