### ISSUE TITLE
No stop() method called on cached controllers

### ISSUE THREAD

**Issue by masterdany88** [NaluKit/nalu#141]
Please add possibility to stop() cached controllers.
We have method:
`        router.clearCache();
`
Whenever We wanna clear caches it is a good place to call stop() method on each cached controllers- f.e.: when You logs out from app.

Second option would be add method f.e.:
`  <C extends AbstractComponentController<?, ?, ?>> void removeFromCacheAllControllers();
`
so when User logs out he can trigger cache clean up.

I think whenever cached controller is removed from cache it should execute its stop() method, cause start method (start caching controller) is executed, but stop method is never executed.

start()/stop() methods starts controllers and its tasks( timers/ handlers etc)
activate()/deactivate() methods are triggered when controller/view is  routed to and out and some task may run in background.

We need to have stop() be triggered.

**Comment by FrankHossfeld** [comment]
see #142
