### ISSUE TITLE
stop() method is never called in cached controllers

### ISSUE THREAD

**Issue by masterdany88** [NaluKit/nalu#142]
Please add possibility to stop() cached controllers.
We have method:
`        router.clearCache();
`
Whenever We wanna clear caches it is a good place to call stop() method on each cached controllers- f.e.: when You logs out from app.

Second option would be add method f.e.:
`  <C extends AbstractComponentController<?, ?, ?>> void removeFromCacheAllControllers();
`
so when User logs out he can trigger cache clean up.

I think whenever cached controller is removed from cache it should execute its stop() method, cause start method (start caching controller) is executed, but stop method is never executed.

start()/stop() methods starts controllers and its tasks( timers/ handlers etc)
activate()/deactivate() methods are triggered when controller/view is  routed to and out and some task may run in background.

We need to have stop() be triggered.

**Comment by FrankHossfeld** [comment]
Some assumptions:

__**ComponentController**__
**storeInCache(this)**
Adds the controller to the store of cached controllers. Call this method from inside the controller you like to cache.
This method will not call the `start`- and `activate`-method of the controller.

**removeFromCache(this)**
Removes the controller from the store of cached controllers.  Call this method from inside the controller you like to remove from the cache. In case the controller is not cached, the method does nothing.
This method will not call the `deactivate`- and `stop`-method of the controller.

**clearControllerCache()**
Clears the cache! This method will remove all cached controllers from the store.
For every controller the method will iterate over

* the composites and call `deactivate`- and `stop`-method
* once done, it call the `deactivate`- and `stop`-method of the controller.

**DO NOT CALL THIS METHOD INSIDE A CACHED CONTROLLER!**
If you are inside a cached controller, call `removeFromCache(this)` first!

__**ComponentCompositeController**__
**storeInCache(this)**
Adds the controller to the store of cached controllers. Call this method from inside the controller you like to cache.
This method will not call the `start`- and `activate`-method of the controller.

**removeFromCache(this)**
Removes the controller from the store of cached controllers.  Call this method from inside the controller you like to remove from the cache. In case the controller is not cached, the method does nothing.
This method will not call the `deactivate`- and `stop`-method of the controller.

**clearControllerCache()**
Clears the cache! This method will remove all cached controllers from the store.
For every controller the method will call the `deactivate`- and `stop`-method of the controller.
**DO NOT CALL THIS METHOD INSIDE A CACHED CONTROLLER!**
If you are inside a cached controller, call `removeFromCache(this)` first!

**Comment by FrankHossfeld** [comment]
Please, switch the Nalu version to HEAD-SNAPSHOT and try again. Just deployed a new SNAPSHOT version containing the fix. Keep in mind, that the Debug annotation is no longer supported. Just delete the code, if you have used it.
If you ran into problems reopen the issue

**Comment by FrankHossfeld** [comment]
Fixed
