### ISSUE TITLE
activate() method is not triggered when You enter again to cached presenter

### ISSUE THREAD

**Issue by masterdany88** [NaluKit/nalu#143]
Activate method is not triggered when You reenter to cached presenter
Deactivate method is triggered always when You leave cached presenter
Seams like inconcistency for me
Activate method is triggered only once at start, when You enter first time cached presenter.
But every time You are leaving cached presenter method deactivate() is triggered.

Issue occurs only when You declare caching in top of composites Controller like this:
```
@Controller(
        route = Routes.NETWORK_CONFIGURATION,
        selector = HTMLSelectors.CONTENT,
        componentInterface = INetworkComponent.class,
        component = NetworkComponent.class
)
@Composites({
        @Composite(name = NetworkHTMLSelectors.NETWORK_CONFIGURATION_LAN_SELECTOR,
                compositeController = LanController.class,
                selector = NetworkHTMLSelectors.NETWORK_CONFIGURATION_LAN_SELECTOR),
        @Composite(name = NetworkHTMLSelectors.NETWORK_CONFIGURATION_WIFI_SELECTOR,
                compositeController = WifiController.class,
                selector = NetworkHTMLSelectors.NETWORK_CONFIGURATION_WIFI_SELECTOR),
})
public class NetworkController extends AbstractComponentController<QBAPContext, INetworkComponent, HTMLElement>
        implements INetworkComponent.Controller {

    @Override
    public void start() {
        router.storeInCache(this);
    }
}
```

When I declare caching in inner controller then it is ok I got active method one each entering and I got deactivate on each leaving .f.e.:
````
@CompositeController(
        componentInterface = IWifiComponent.class,
        component = WifiComponent.class
)
public class WifiController extends AbstractCompositeController<QBAPContext, IWifiComponent, HTMLElement> implements IWifiComponent.Controller {
        router.storeInCache(this);
}  
```

**Comment by FrankHossfeld** [comment]
to make it clear: we are talking about the `activate`-method of a CompositeComponentController inside a cached ComponentController. The `activate`-method the cached ComponentController is called. 

Correct?

**Comment by FrankHossfeld** [comment]
The activate method of the composites get called. Fixed!
