### ISSUE TITLE
UiBinder template

### ISSUE THREAD

**Issue by jhonToni** [NaluKit/nalu#156]
In `nalu` can I load a `template` from a xml file ?

Template example: 

```
<ui:UiBinder
  xmlns:ui="urn:ui:com.google.gwt.uibinder"
  xmlns:g="urn:import:com.google.gwt.user.client.ui">

  <ui:style>
    .contactsViewButtonHPanel {
      margin: 5px 0px 0x 5px;
    }
    .contactsViewContactsFlexTable {
      margin: 5px 0px 5px 0px;
    }

  </ui:style>

  <g:DecoratorPanel>
    <g:VerticalPanel>
      <g:HorizontalPanel addStyleNames="{style.contactsViewButtonHPanel}">
        <g:Button ui:field="addButton">Add</g:Button>
        <g:Button ui:field="deleteButton">Delete</g:Button>
      </g:HorizontalPanel>
      <g:FlexTable ui:field="contactsTable" addStyleNames="{style.contactsViewContactsFlexTable}"/>
    </g:VerticalPanel>
  </g:DecoratorPanel>
</ui:UiBinder>
```

**Comment by FrankHossfeld** [comment]
Yes, of course! You need to use the Nalu-GWT-Plugin. You will find an example here: [https://github.com/NaluKit/nalu-examples/tree/master/NaluGwtSimpleApplication](https://github.com/NaluKit/nalu-examples/tree/master/NaluGwtSimpleApplication). The example does not use UiBinder, but you can add the UiBinder to any component in that example. I am not familiar really familiar with UiBinder, but it should work out of the box. If not, feel free to use the [Nalu Gitter room](https://gitter.im/Nalukit42/Lobby).

**Comment by FrankHossfeld** [comment]
In case you have problems using UiBinder, reopen the issue or use the Gitter room.
