### ISSUE TITLE
Registered handlers will removed on controller deactivation

### ISSUE THREAD

**Issue by TDesjardins** [NaluKit/nalu#162]
Event handlers could be registered in controllers with the advantage that they will be automatically removed when the controller stops. Currently they will be also removed on deactivation. If you use cached controllers and then use global events via event bus to  exchange information the not active controller won't get that event if the handler is registered (`com.github.nalukit.nalu.client.internal.HandlerRegistrations`).
One solution is to not register global eventhandlers and care about the clean up. Another solution is to provide an an additional event registration for global events which will only clean up on controller stop.

**Comment by FrankHossfeld** [comment]
The second solution: **Another solution is to provide an an additional event registration for global events which will only clean up on controller stop.** sounds good.

**Comment by FrankHossfeld** [comment]
Done.

**Comment by FrankHossfeld** [comment]
More informations here: https://github.com/NaluKit/nalu/wiki/14.-Controllers-&-Components#handler-management
