### ISSUE TITLE
Maven build failure

### ISSUE THREAD

**Issue by hossein-tabei** [NaluKit/nalu#165]
Hi
When I tried to run Nalu examples in eclipse, I faced with the following error during build with maven:

<pre>
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.gihub.nalukit.example:NaluControllerMultipleRoute-client:gwt-app:HEAD-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.github.nalukit:nalu:jar -> version ${nalu.version} vs HEAD-SNAPSHOT @ line 89, column 17
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.github.nalukit.example.nalu:NaluGwtSimpleApplication:gwt-app:HEAD-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-maven-plugin is missing. @ line 157, column 15
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.github.nalukit.example.nalu:NaluGxtSimpleApplication:gwt-app:HEAD-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-maven-plugin is missing. @ line 192, column 15
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.github.nalukit.example.nalu:NaluMaterialSimpleApplication:gwt-app:HEAD-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-maven-plugin is missing. @ line 192, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] devkexample - Nalu Boot Starter Project                            [pom]
[INFO] devkexample-shared                                                 [jar]
[INFO] devkexample-client                                             [gwt-app]
[INFO] devkexample-server                                                 [war]
[INFO] NaluControllerMultipleRoute - Nalu Boot Starter Project            [pom]
[INFO] NaluControllerMultipleRoute-shared                                 [jar]
[INFO] NaluControllerMultipleRoute-client                             [gwt-app]
[INFO] NaluControllerMultipleRoute-server                                 [war]
[INFO] NaluDominoCachedApplication                                    [gwt-app]
[INFO] NaluDominoCompositeCachedApplication                           [gwt-app]
[INFO] NaluDominoLoginApplication                                     [gwt-app]
[INFO] NaluDominoLoginModuleApplication - Nalu Example Project            [pom]
[INFO] NaluDominoLoginModuleApplication-shared                            [jar]
[INFO] NaluDominoLoginModuleApplication-login                         [gwt-lib]
[INFO] NaluDominoLoginModuleApplication-client                        [gwt-app]
[INFO] NaluDominoLoginModuleApplication-server                            [war]
[INFO] NaluDominoLoginNoHashModuleApplication                             [pom]
[INFO] NaluDominoLoginNoHashModuleApplication-shared                      [jar]
[INFO] NaluDominoLoginNoHashModuleApplication-login                   [gwt-lib]
[INFO] NaluDominoLoginNoHashModuleApplication-client                  [gwt-app]
[INFO] NaluDominoLoginNoHashModuleApplication-server                      [war]
[INFO] NaluDominoSimpleApplication                                    [gwt-app]
[INFO] NaluDominoSimplePopUpApplication                               [gwt-app]
[INFO] NaluGwtSimpleApplication                                       [gwt-app]
[INFO] NaluGxtSimpleApplication                                       [gwt-app]
[INFO] NaluMaterialSimpleApplication                                  [gwt-app]
[INFO] Nalu Example parent                                                [pom]
[INFO] 
[INFO] -------------------< de.gishmo.example:devkexample >--------------------
[INFO] Building devkexample - Nalu Boot Starter Project HEAD-SNAPSHOT    [1/27]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ devkexample ---
[INFO] Installing C:\Users\Hossein\Downloads\Compressed\nalu-examples-master\devkexample\pom.xml to C:\Users\Hossein\.m2\repository\de\gishmo\example\devkexample\HEAD-SNAPSHOT\devkexample-HEAD-SNAPSHOT.pom
[INFO] 
[INFO] ----------------< de.gishmo.example:devkexample-shared >----------------
[INFO] Building devkexample-shared HEAD-SNAPSHOT                         [2/27]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-rest-shared/1.0-rc.4-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-rest-shared/1.0-rc.4-SNAPSHOT/maven-metadata.xml (1.2 kB at 588 B/s)
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-rest/1.0-rc.4-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-rest/1.0-rc.4-SNAPSHOT/maven-metadata.xml (609 B at 1.3 kB/s)
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/gwtproject/regexp/gwt-regexp/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://repo.vertispan.com/gwt-snapshot/org/gwtproject/regexp/gwt-regexp/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/gwtproject/regexp/gwt-regexp/1.0-SNAPSHOT/maven-metadata.xml (778 B at 1.6 kB/s)
[WARNING] Could not transfer metadata org.gwtproject.regexp:gwt-regexp:1.0-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer org.gwtproject.regexp:gwt-regexp:1.0-SNAPSHOT/maven-metadata.xml from https://repo.vertispan.com/gwt-snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of vertispan-snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.gwtproject.regexp:gwt-regexp:1.0-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading from : https://repo.vertispan.com/gwt-snapshot/org/dominokit/jaxrs-super/1.0-rc.4-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/jaxrs-super/1.0-rc.4-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/jaxrs-super/1.0-rc.4-SNAPSHOT/maven-metadata.xml (1.2 kB at 2.5 kB/s)
[WARNING] Could not transfer metadata org.dominokit:jaxrs-super:1.0-rc.4-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer org.dominokit:jaxrs-super:1.0-rc.4-SNAPSHOT/maven-metadata.xml from https://repo.vertispan.com/gwt-snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of vertispan-snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.dominokit:jaxrs-super:1.0-rc.4-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading from : https://repo.vertispan.com/gwt-snapshot/org/dominokit/jackson/jackson-apt/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/jackson/jackson-apt/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/jackson/jackson-apt/1.0-SNAPSHOT/maven-metadata.xml (1.2 kB at 2.5 kB/s)
[WARNING] Could not transfer metadata org.dominokit.jackson:jackson-apt:1.0-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer org.dominokit.jackson:jackson-apt:1.0-SNAPSHOT/maven-metadata.xml from https://repo.vertispan.com/gwt-snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of vertispan-snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.dominokit.jackson:jackson-apt:1.0-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/jackson/domino-jackson/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://repo.vertispan.com/gwt-snapshot/org/dominokit/jackson/domino-jackson/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/jackson/domino-jackson/1.0-SNAPSHOT/maven-metadata.xml (610 B at 1.2 kB/s)
[WARNING] Could not transfer metadata org.dominokit.jackson:domino-jackson:1.0-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/jackson/jackson-super/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://repo.vertispan.com/gwt-snapshot/org/dominokit/jackson/jackson-super/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/jackson/jackson-super/1.0-SNAPSHOT/maven-metadata.xml (1.2 kB at 2.4 kB/s)
[WARNING] Could not transfer metadata org.dominokit.jackson:jackson-super:1.0-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer org.dominokit.jackson:jackson-super:1.0-SNAPSHOT/maven-metadata.xml from https://repo.vertispan.com/gwt-snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of vertispan-snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.dominokit.jackson:jackson-super:1.0-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/gwtproject/i18n/gwt-cldr/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://repo.vertispan.com/gwt-snapshot/org/gwtproject/i18n/gwt-cldr/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/gwtproject/i18n/gwt-cldr/1.0-SNAPSHOT/maven-metadata.xml (983 B at 247 B/s)
[WARNING] Could not transfer metadata org.gwtproject.i18n:gwt-cldr:1.0-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer org.gwtproject.i18n:gwt-cldr:1.0-SNAPSHOT/maven-metadata.xml from https://repo.vertispan.com/gwt-snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of vertispan-snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.gwtproject.i18n:gwt-cldr:1.0-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/gwtproject/i18n/gwt-datetimeformat/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://repo.vertispan.com/gwt-snapshot/org/gwtproject/i18n/gwt-datetimeformat/1.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.gwtproject.i18n:gwt-datetimeformat:1.0-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer org.gwtproject.i18n:gwt-datetimeformat:1.0-SNAPSHOT/maven-metadata.xml from https://repo.vertispan.com/gwt-snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of vertispan-snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.gwtproject.i18n:gwt-datetimeformat:1.0-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/gwtproject/i18n/gwt-datetimeformat/1.0-SNAPSHOT/gwt-datetimeformat-1.0-SNAPSHOT.pom
[INFO] Downloading from : https://repo.vertispan.com/gwt-snapshot/org/gwtproject/i18n/gwt-datetimeformat/1.0-SNAPSHOT/gwt-datetimeformat-1.0-SNAPSHOT.pom
[INFO] Downloading from : https://repo.vertispan.com/gwt-snapshot/org/dominokit/domino-aggregator-shared/1.0-rc.4-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-aggregator-shared/1.0-rc.4-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-aggregator-shared/1.0-rc.4-SNAPSHOT/maven-metadata.xml (1.2 kB at 2.5 kB/s)
[WARNING] Could not transfer metadata org.dominokit:domino-aggregator-shared:1.0-rc.4-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer org.dominokit:domino-aggregator-shared:1.0-rc.4-SNAPSHOT/maven-metadata.xml from https://repo.vertispan.com/gwt-snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of vertispan-snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.dominokit:domino-aggregator-shared:1.0-rc.4-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading from : https://repo.vertispan.com/gwt-snapshot/org/dominokit/domino-aggregator/1.0-rc.4-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-aggregator/1.0-rc.4-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-aggregator/1.0-rc.4-SNAPSHOT/maven-metadata.xml (613 B at 145 B/s)
[WARNING] Could not transfer metadata org.dominokit:domino-aggregator:1.0-rc.4-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-history-shared/1.0-rc.4-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://repo.vertispan.com/gwt-snapshot/org/dominokit/domino-history-shared/1.0-rc.4-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-history-shared/1.0-rc.4-SNAPSHOT/maven-metadata.xml (1.2 kB at 188 B/s)
[WARNING] Could not transfer metadata org.dominokit:domino-history-shared:1.0-rc.4-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer org.dominokit:domino-history-shared:1.0-rc.4-SNAPSHOT/maven-metadata.xml from https://repo.vertispan.com/gwt-snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of vertispan-snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.dominokit:domino-history-shared:1.0-rc.4-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-history/1.0-rc.4-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://repo.vertispan.com/gwt-snapshot/org/dominokit/domino-history/1.0-rc.4-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-history/1.0-rc.4-SNAPSHOT/maven-metadata.xml (612 B at 1.2 kB/s)
[WARNING] Could not transfer metadata org.dominokit:domino-history:1.0-rc.4-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-rest-apt/1.0-rc.4-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/domino-rest-apt/1.0-rc.4-SNAPSHOT/maven-metadata.xml (1.2 kB at 2.5 kB/s)
[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/jackson/jackson-apt-processor/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from : https://repo.vertispan.com/gwt-snapshot/org/dominokit/jackson/jackson-apt-processor/1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from : https://oss.sonatype.org/content/repositories/snapshots/org/dominokit/jackson/jackson-apt-processor/1.0-SNAPSHOT/maven-metadata.xml (1.2 kB at 2.1 kB/s)
[WARNING] Could not transfer metadata org.dominokit.jackson:jackson-apt-processor:1.0-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer org.dominokit.jackson:jackson-apt-processor:1.0-SNAPSHOT/maven-metadata.xml from https://repo.vertispan.com/gwt-snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of vertispan-snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.dominokit.jackson:jackson-apt-processor:1.0-SNAPSHOT/maven-metadata.xml from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] devkexample - Nalu Boot Starter Project HEAD-SNAPSHOT SUCCESS [  0.474 s]
[INFO] devkexample-shared HEAD-SNAPSHOT ................... FAILURE [01:14 min]
[INFO] devkexample-client HEAD-SNAPSHOT ................... SKIPPED
[INFO] devkexample-server HEAD-SNAPSHOT ................... SKIPPED
[INFO] NaluControllerMultipleRoute - Nalu Boot Starter Project HEAD-SNAPSHOT SKIPPED
[INFO] NaluControllerMultipleRoute-shared HEAD-SNAPSHOT ... SKIPPED
[INFO] NaluControllerMultipleRoute-client HEAD-SNAPSHOT ... SKIPPED
[INFO] NaluControllerMultipleRoute-server HEAD-SNAPSHOT ... SKIPPED
[INFO] NaluDominoCachedApplication HEAD-SNAPSHOT .......... SKIPPED
[INFO] NaluDominoCompositeCachedApplication HEAD-SNAPSHOT . SKIPPED
[INFO] NaluDominoLoginApplication HEAD-SNAPSHOT ........... SKIPPED
[INFO] NaluDominoLoginModuleApplication - Nalu Example Project HEAD-SNAPSHOT SKIPPED
[INFO] NaluDominoLoginModuleApplication-shared HEAD-SNAPSHOT SKIPPED
[INFO] NaluDominoLoginModuleApplication-login HEAD-SNAPSHOT SKIPPED
[INFO] NaluDominoLoginModuleApplication-client HEAD-SNAPSHOT SKIPPED
[INFO] NaluDominoLoginModuleApplication-server HEAD-SNAPSHOT SKIPPED
[INFO] NaluDominoLoginNoHashModuleApplication HEAD-SNAPSHOT SKIPPED
[INFO] NaluDominoLoginNoHashModuleApplication-shared HEAD-SNAPSHOT SKIPPED
[INFO] NaluDominoLoginNoHashModuleApplication-login HEAD-SNAPSHOT SKIPPED
[INFO] NaluDominoLoginNoHashModuleApplication-client HEAD-SNAPSHOT SKIPPED
[INFO] NaluDominoLoginNoHashModuleApplication-server HEAD-SNAPSHOT SKIPPED
[INFO] NaluDominoSimpleApplication HEAD-SNAPSHOT .......... SKIPPED
[INFO] NaluDominoSimplePopUpApplication HEAD-SNAPSHOT ..... SKIPPED
[INFO] NaluGwtSimpleApplication HEAD-SNAPSHOT ............. SKIPPED
[INFO] NaluGxtSimpleApplication HEAD-SNAPSHOT ............. SKIPPED
[INFO] NaluMaterialSimpleApplication HEAD-SNAPSHOT ........ SKIPPED
[INFO] Nalu Example parent 2.1.0-SNAPSHOT ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:19 min
[INFO] Finished at: 2020-11-03T18:29:52+03:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project devkexample-shared: Could not resolve dependencies for project de.gishmo.example:devkexample-shared:jar:HEAD-SNAPSHOT: Failed to collect dependencies at org.dominokit:domino-rest-shared:jar:1.0-rc.4-SNAPSHOT -> org.dominokit.jackson:jackson-apt:jar:1.0-SNAPSHOT -> org.gwtproject.i18n:gwt-datetimeformat:jar:1.0-SNAPSHOT: Failed to read artifact descriptor for org.gwtproject.i18n:gwt-datetimeformat:jar:1.0-SNAPSHOT: Could not transfer artifact org.gwtproject.i18n:gwt-datetimeformat:pom:1.0-SNAPSHOT from/to vertispan-snapshots (https://repo.vertispan.com/gwt-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :devkexample-shared
</pre>

I'm new in maven. Please help me.

**Comment by FrankHossfeld** [comment]
This problem is not related to Nalu. It looks like there is a problem with the vertispan repo, which serves some of the SNAPSHOTS or your Maven configuration. Alternative, you may have problems accessing the repo (proxy, fire wall, etc.)

I am just running a `mvn clean verify` and it works:

````
Reactor Summary:
[INFO] 
[INFO] devkexample - Nalu Boot Starter Project HEAD-SNAPSHOT SUCCESS [  0.002 s]
[INFO] devkexample-shared HEAD-SNAPSHOT ................... SUCCESS [  7.408 s]
[INFO] devkexample-client HEAD-SNAPSHOT ................... SUCCESS [ 42.356 s]
[INFO] devkexample-server HEAD-SNAPSHOT ................... SUCCESS [  4.532 s]
[INFO] NaluControllerMultipleRoute - Nalu Boot Starter Project HEAD-SNAPSHOT SUCCESS [  0.000 s]
[INFO] NaluControllerMultipleRoute-shared HEAD-SNAPSHOT ... SUCCESS [  0.061 s]
[INFO] NaluControllerMultipleRoute-client HEAD-SNAPSHOT ... SUCCESS [ 30.017 s]
[INFO] NaluControllerMultipleRoute-server HEAD-SNAPSHOT ... SUCCESS [  2.396 s]
[INFO] NaluDominoCachedApplication HEAD-SNAPSHOT .......... SUCCESS [ 35.719 s]
[INFO] NaluDominoCompositeCachedApplication HEAD-SNAPSHOT . SUCCESS [ 37.044 s]
[INFO] NaluDominoLoginApplication HEAD-SNAPSHOT ........... SUCCESS [ 35.827 s]
[INFO] NaluDominoLoginModuleApplication - Nalu Example Project HEAD-SNAPSHOT SUCCESS [  0.000 s]
[INFO] NaluDominoLoginModuleApplication-shared HEAD-SNAPSHOT SUCCESS [  0.071 s]
[INFO] NaluDominoLoginModuleApplication-login HEAD-SNAPSHOT SUCCESS [  0.631 s]
[INFO] NaluDominoLoginModuleApplication-client HEAD-SNAPSHOT SUCCESS [ 33.043 s]
[INFO] NaluDominoLoginModuleApplication-server HEAD-SNAPSHOT SUCCESS [  2.368 s]
[INFO] NaluDominoLoginNoHashModuleApplication HEAD-SNAPSHOT SUCCESS [  0.001 s]
[INFO] NaluDominoLoginNoHashModuleApplication-shared HEAD-SNAPSHOT SUCCESS [  0.072 s]
[INFO] NaluDominoLoginNoHashModuleApplication-login HEAD-SNAPSHOT SUCCESS [  0.335 s]
[INFO] NaluDominoLoginNoHashModuleApplication-client HEAD-SNAPSHOT SUCCESS [ 30.493 s]
[INFO] NaluDominoLoginNoHashModuleApplication-server HEAD-SNAPSHOT SUCCESS [  2.473 s]
[INFO] NaluDominoSimpleApplication HEAD-SNAPSHOT .......... SUCCESS [ 33.549 s]
[INFO] NaluDominoSimplePopUpApplication HEAD-SNAPSHOT ..... SUCCESS [ 34.839 s]
[INFO] NaluGwtSimpleApplication HEAD-SNAPSHOT ............. SUCCESS [ 28.028 s]
[INFO] NaluGxtSimpleApplication HEAD-SNAPSHOT ............. SUCCESS [03:38 min]
[INFO] NaluMaterialSimpleApplication HEAD-SNAPSHOT ........ SUCCESS [ 25.435 s]
[INFO] Nalu Example parent 2.1.0-SNAPSHOT ................. SUCCESS [  0.001 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:06 min
[INFO] Finished at: 2020-11-03T18:37:23+01:00
[INFO] ------------------------------------------------------------------------
````

Please try again. 

In case it does not work, please use the Nalu Gitter room: https://gitter.im/Nalukit42/Lobby

**Comment by hossein-tabei** [comment]
Hi Frank,
Thank you for your response. I will try again.
