### ISSUE TITLE
Nalu Modules: start route can only be a route of the main module

### ISSUE THREAD

**Issue by timmarsha11** [NaluKit/nalu#178]
When using the demo modular applications (NaluDominoLoginNoHashModuleApplication / NaluDominoLoginModuleApplication) , the client will start but a popup 'startRoute not valid - application stopped!' is displayed. 

The startRoute in the demo is set to 'shellLogin/Login' route, which is in the login module, not the main application module.

If startRoute is set to a route defined in the main application, the demo works as expected, and the filter diverts the user to login via the login module.

Hence the framework code currently only works if the startRoute is defined in the main application module.

In the internal AbstractApplication, this.loadDefaultRoutes(); is called at line 108, before this.onFinishLoading() at line 167/172, which in turn call this.loadModules();, which registers the routes from the modules. 

If possible, change the AbstractApplication class to loadDefaultRoutes() after the loadModules() call has been made. This should allow the startRoute to be defined by the modules, assuming nothing else is broken in the process.

**Comment by FrankHossfeld** [comment]
Fixed
