### ISSUE TITLE
Make Eventbus available from Filters

### ISSUE THREAD

**Issue by timmarsha11** [NaluKit/nalu#179]
At present the eventbus is only available for logging errors in filters. It has private access in the AbstractFilter class.

Proposed to make the eventbus available for general events (especially logging) when the filter is activated i.e making it protected access.

**Comment by FrankHossfeld** [comment]
I do not see any reason why the event bus should not have protected access.

**Comment by timmarsha11** [comment]
Hi, it seems that the eventBus is not populated in the filter (its null when I try and use it).

My project setup uses a LoginModule. In the LoginFilter class, I try and send a message to the eventBus but the eventBus is null. 
....
@Override
public boolean filter(String route, String... parms) {
		if (!LoginModuleRoutes.LOGIN_ROUTE.equals(route)) {
			if (!this.context.isLoggedIn()) {
				this.eventBus.fireEvent(LogEvent.create().addMessage("User is not logged in! Redirect to Login screen!"));
				
				return false;
			}
		}
		return true;
	}
...

In the generated LoginModuleModuleImpl class, I suspect the eventbus needs to be set in this method, when the context is set???

@Override
  public void loadFilters(RouterConfiguration routerConfiguration) {
    LoginFilter client_module_login_filter_LoginFilter = new LoginFilter();
    client_module_login_filter_LoginFilter.setContext(super.moduleContext);
**client_module_login_filter_LoginFilter.setEventBus(super.eventBus)**
    routerConfiguration.getFilters().add(client_module_login_filter_LoginFilter);
  }

**Comment by FrankHossfeld** [comment]
Mmmh, I checked the filters of my project. and in all filters the event bus is set.
I am pretty sure, you are using an old version. ATM this feature is only available inside the latest SNAPSHOT.

**Comment by FrankHossfeld** [comment]
Oh, I missed the module generator ... please try again

**Comment by timmarsha11** [comment]
> Oh, I missed the module generator ... please try again

yep this is now working in HEAD-SNAPSHOT

**Comment by FrankHossfeld** [comment]
Thanks for confirming
