### ISSUE TITLE
Possibility to reset URL (delete parameters from URL)

### ISSUE THREAD

**Issue by ManuelPenker** [NaluKit/nalu#192]
Hello together,

In some cases I need to reset the given URL parameter e.g. http://localhost:8080/?param=1234#app/start to http://localhost:8080/#app/start. 
Nalu have a method like router.getStartQueryParameters().clear(); but this only clears the parameters in the list. The parameters are still in the URL.

Is there a possibility to implement a method to reset the URL?

Thank you.

Kindly regards 
Manuel Penker

**Comment by FrankHossfeld** [comment]
Hello,

of course we can take a look and implement that feature. The easiest way to do that, is adding a new attribute to the @Application annotation. Something like 'removeUrlParameterAtStart". A value of 'true' will remove the url parameters.

The default value will be false,

Would that work for you?

**Comment by ManuelPenker** [comment]
Sounds good :). This is ok for me.

**Comment by FrankHossfeld** [comment]
Done
