### ISSUE TITLE
Add support for passing object parameters to PopUpControllers

### ISSUE THREAD

**Issue by wernz0r** [NaluKit/nalu#245]
The datastore of a PopUpController currently only accepts String values when calling the `using` method. Thus one can only pass references (e.g. ids) to a PopUpController. Inside the PopUpcontroller the corresponding data objects must be retrieved by using this references. This usually leads to extra server-client communication just to retrieve the needed data.

It would be awesome, if one could also pass object values to the datastore of a PopUpController. This would reduce the number of client-server requests.

**Comment by FrankHossfeld** [comment]
Regarding the fact, that this is the second time this feature is requested we will check it.

**Comment by FrankHossfeld** [comment]
Done
