### ISSUE TITLE
IsCustomConfirmPresenter enhancement 

### ISSUE THREAD

**Issue by masterdany88** [NaluKit/nalu#253]
Currently CustomConfirmPresenter Do not get injected eventbus, router, context- Like other presenter. I think It should be added. My impl example:

```
public class DropChangesConfirmationDialog implements IsCustomConfirmPresenter {

    private IsNaluProcessorPlugin.ConfirmHandler confirmHandler;

    @Override
    public void confirm(String message) {
        Dialog.createWithConfirmation(UiComponentType.WARNING, TRANSLATIONS.discardChanges(), "",
                TRANSLATIONS.discard(), okButtonEvent -> confirmHandler.onOk(), cancelButtonEvent -> confirmHandler.onCancel()).open();
    }

    @Override
    public void addConfirmHandler(IsNaluProcessorPlugin.ConfirmHandler confirmHandler) {
        this.confirmHandler = confirmHandler;
    }
}
```

Also Current CustomConfirmPresetner get injected ConfimHandler that in his method onCancel executes as follow:
```
        public void onCancel() {
            AbstractRouter.this.plugin.route(AbstractRouter.this.lastExecutedHash, false, false);
            AbstractRouter.this.loopDetectionList.clear();
        }
```

Which do revert hash (in url browser) and keep on existing view, but doesnt handle navigation menu selected entry.
So on cancel I am staying on current page, routing is aborted, url in browser is reverted to current page, but unfortunatelly new link clicked is highlighted in menu. This is not rollbacked.
on cancel method should contain logic, that fires routing event as follow:
`RouterStateEvent`

`
        this.eventBus.fireEvent(new RouterStateEvent(state, route, params));
`
then user could catch and handle such event to highlight valid menu entry base on routing, f.e.:
```

    public void highlightMenuEntry(RouterStateEvent e) {
        getComponent().getTree().deactivateAll();
        getComponent().getTree().getSubItems()
                .stream()
                .filter(i -> NaluUtils.get().compareRoutes(i.getValue().getRoute(), e.getRoute()))
                .findFirst()
                .ifPresent(TreeItem::activate);
    }

```

**Comment by FrankHossfeld** [comment]
Adding a new RouterState and firing a RouterStateEvent in case the user canceled the routing will be the preferred solution. Thanks for the PR.

**Comment by FrankHossfeld** [comment]
Keep in mind, Nalu does not know, what happens the last time. Once a routing is done, there are no information about the last routing anymore.

If I understand your requirements correct, you will:
select navigation -> mark navigation -> remove mark of old navigation -> route.

In case the user canceled the routing, you will:
select navigation -> mark navigation -> remove mark of old navigation -> route -> cancel routing -> remove mark for new selection from navigation -> mark old navigation.

In my opinion, you have to do it in this way (with no canceling):
select navigation -> route ->  controller (new one loaded by Nalu) `start`- or `active`-method -> fire updateNavigationEvent  (using `relatedRoute` from controller) -> catch event in navigation controller -> mark navigation item selected

So, a user canceling will have no impact of the navigation.

I think, this is the only way that will always work in any case.

**Comment by FrankHossfeld** [comment]
I'll close the issue, bc the event is implemented and the values of the event are correct. Regarding your question, feel free to contact me inside the Gitter room.
