### ISSUE TITLE
gwt:codeserver after few reloads make nalu forget version properties

### ISSUE THREAD

**Issue by masterdany88** [NaluKit/nalu#265]
```
/**
 * Build with Nalu version >>2.9.0<< at >>2022.05.09-18:22:50<<
 */
public final class APApplicationImpl extends AbstractApplication<APContext> implements APApplication {
  public APApplicationImpl() {
    super();
    super.context = new com.gan.sphere.ap.ui.APContext();
    super.context.setApplicationVersion("APPLCIATION-VERSION-NOT-AVAILABLE");
    super.context.setApplicationBuildTime(new Date(1652113372775L));
  }
```

my maven gwt module:
```
            <plugin>
                <groupId>net.ltgt.gwt.maven</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>${gwt-maven-plugin.version}</version>
                <inherited>false</inherited>
                <extensions>true</extensions>
                <configuration>
                    <failOnError>true</failOnError>
                    <sourceLevel>1.8</sourceLevel>
                    <launcherDir>${project.build.directory}/gwt/launcherDir</launcherDir>
                    <moduleShortName>ap</moduleShortName>
                    <systemProperties>
                        <systemProperty>
                            <name>nalu.application.version</name>
                            <value>${project.version}</value>
                        </systemProperty>
                    </systemProperties>
                </configuration>
            </plugin>
```

**Comment by FrankHossfeld** [comment]
I can not imagine how Nalu should treat commands different after a few reloads.

Do you have a small project, that shows the bug?

**Comment by masterdany88** [comment]
unfortunatelly not.
My version after clean install: 
    super.context.setApplicationVersion("2.42.0.SNAPSHOT");
but it is gone after few reloads

**Comment by masterdany88** [comment]
What I found out, is that after triggering build (on whole project) in intelij ctrl + F9 or ctrl + 9 (base on os) I am losing this version in nalu.
Build in intelij j triggers java annotation process (but without any maven goals)
I assume that nalu gets this value in maven build

**Comment by masterdany88** [comment]
Can I somehow tell nalu the version if there was no maven, but only annotation processes triggered?
Some properties file f.e?

**Comment by FrankHossfeld** [comment]
Setting the version can be done by using the version annotation: https://github.com/NaluKit/nalu/wiki/06.-Application#version-and-build-time

Not sure, if this is a suitable solution for you.

**Comment by FrankHossfeld** [comment]
I'll close the issue. Looks like there is nothing to do ...
