### ISSUE TITLE
Test Templates show some hard coded HEAD-SNAPSHOT version

### ISSUE THREAD

**Issue by philkohl** [NaluKit/nalu#272]
A few test templates have hard coded HEAD-SNAPSHOT instead of the abstract tag (see com/github/nalukit/nalu/processor.templates/shellCreator/eventhandler/eventHandlerOnAShellCreatorOk03/TestApplicationImpl.java:2) 
This can lead to failing test cases when not called with HEAD-SNAPSHOT.

**Comment by FrankHossfeld** [comment]
@philkohl I think we can close this issue. Can we?
