### ISSUE TITLE
Add getContext() and getRouter() in AbstractController

### ISSUE THREAD

**Issue by DevFlorian** [NaluKit/nalu#36]
It would be nice, if you would add getContext() and getRouter() in AbstractController to use it more comfortable in anonymous Classes.

**Comment by FrankHossfeld** [comment]
Mmmh, not sure, if this is really necessary. Please, can you provide an example.

**Comment by DevFlorian** [comment]
Yeah, you're right. It's not necessary.

**Comment by FrankHossfeld** [comment]
@DevFlorian You can contact me on Gitter using the Nalu Gitter room In case you have any questions or to discuss your requirement.
