### ISSUE TITLE
Make conditionals composite components

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [NaluKit/nalu#46]
It would be nice if composite component could be conditional. For example, if you have one page with the same content and depending on who has been logged in, you can have one composite component or another

**Comment by FrankHossfeld** [comment]
Hi Raul,
sorry for the delay. I will work on the feature the next days.

My plan is to add an optional attribute to the `@composite`-annotation. Lets call the attribute **condition** (if you have a better idea, please let me know) In case this attribute is not set, Nalu will behave as it did before and add the composite to the selector. 

The **condition**-attribute expects a class that extends the abstract `CompositeCondition`-class. The class will look like that:
```java
public abstract class CompositeCondition<C extends IsContext> {

  protected C context;

  public abstract boolean onRequestCompositeLoad();

}
```
 Inside the `onRequestCompositeLoad`-method you can decide weather you like to load the composite or not by returning **true** to load the composite and **false** to not load the composite.

Do you think this will help you?

**Comment by RaulPampliegaMayoral** [comment]
Hi Frank, I think this solution will work for ours needs, having access to the context in order to check if the composite must be attached.

**Comment by FrankHossfeld** [comment]
Hi Raul,
I have implemented feature.

Docs:
https://github.com/NaluKit/nalu/wiki/09.-Controller-&-Component#conditional-composite-since-v122

Example:
https://github.com/NaluKit/nalu-examples/tree/master/NaluDominoSimpleApplication
The DetailController uses the new feature. Run the example and  select Homer Simpson. The detail screen will show another card. Select a different person and you won't see the card.

 In case you find a bug or ran into problems, open another issue or use the Gitter room.

Frank

**Comment by RaulPampliegaMayoral** [comment]
Hi Frank, I've looked at it and it looks promising

**Comment by FrankHossfeld** [comment]
Let me know, if you can use it successfully. If everything works well, I will create a new release in two weeks or so.

**Comment by RaulPampliegaMayoral** [comment]
Hi Frank! Finally i can test the conditional composite.

It can be possible to have access to the context on the conditional class? Our use case depends on a property from the context the condition to choose one component or another.

**Comment by FrankHossfeld** [comment]
Ups!  you are right! I have added the context to the `AbstractCompositeCondition` class, but it's private! 
Will change it tonight (hope, that's early enough.)

**Comment by RaulPampliegaMayoral** [comment]
Hi Frank! It will ok, thanks

I must to say that the conditional composition is working well, without problems.

**Comment by FrankHossfeld** [comment]
Fixed ... see #49
