### ISSUE TITLE
Loader functionality for shell

### ISSUE THREAD

**Issue by SaschaMuench** [NaluKit/nalu#50]
The Loader (`AbstractApplicationLoader`) enables the application to load data from server and wait for finishing the load process with `finishLoadCommand.finishLoading();`

A same idea can be used within the Controller (`AbstractComponentController`) in the `bind`-function with `loader.continueLoading();`

In my case I need to load data from the server during the change of the Shell (`AbstractShell`), so that the retrieved data can be added to the context and used in every Controller in this Shell.

The change of the `bind`-function seems to be a breaking change. Maybe a `bindTillFinished`-function would be a possibility to implement this without any breaks.

**Comment by FrankHossfeld** [comment]
I have decided to change the signature of the `bind`-method. Now, the `bind`-method of the shell and the controller behave in the same way. 

To update an existing implementation of a `bind`-method inside a shell:
* add `ShellLoader loader`as parameter to the mehod
* add `throws RoutingInterceptionException`to the `bind`-method
* call `loader.continueLoading();` once you want to leave the method.

**Comment by FrankHossfeld** [comment]
implemented. Please test.
