### ISSUE TITLE
Redirect to start url in case of missing hash

### ISSUE THREAD

**Issue by masterdany88** [NaluKit/nalu#51]
Nalu redirect to error page when there is no hash passed. It should instead redirect to starturl/home which is declared in Nalu Applicatio Configuration.
This is happening only when You start app with no hash url like https://host or https://host/index.html and then go to nalu subpage and then go back using back browser button url back android button.

**Comment by FrankHossfeld** [comment]
Think, I have got it. 

Now, in case going back using the back button, Nalu will replace https://host/index.html with https://host/index.html#startShell/startRoute

Now, the next question: Nalu can replace the url. so the next pressing of the back button will leave the application and you stay on the side before calling the application. Another option is, that the back button will always go the start route (in case it has no hash!)

What do you thing?

**Comment by FrankHossfeld** [comment]
Implemented.

**Comment by masterdany88** [comment]
I Would prefer to stay at app instead of going back to previous page. I don't like this behaviour when I am on RIA, but for web pages is ok. Maybe this behaviour should be configurable?

**Comment by FrankHossfeld** [comment]
Well, the problem about this question is: If you ask two people, you'll get three opinions. I will add a parameter to configurate it. See #52
