### ISSUE TITLE
Implement a "RoutingEvent" after routing was done

### ISSUE THREAD

**Issue by schube** [NaluKit/nalu#58]
Please add a "RoutingEvent" in Nalu, which I can listen for.

Background is: The "current menu" items is highlighted, but when the route changes, the old menu item is still highlighted. I want to change that.

**Comment by FrankHossfeld** [comment]
Done

**Comment by schube** [comment]
Perfect.
But please add the route to the RoutingEvent. Thank you!

**Comment by FrankHossfeld** [comment]
Please open a new issue ... 

thanks
