### ISSUE TITLE
Caching of composite doesn't work as expected

### ISSUE THREAD

**Issue by TDesjardins** [NaluKit/nalu#67]
The new feature "caching composites" doesn't work as expected.

If you have two components A and B configured with a cached composite the following happens:

1. Route to component A -> composite is visible
2. Route to component B -> composite is also visible
3. Route to component A again -> composite isn't visible (**not expected**)
4. Route to component B again -> composite is visible

In both controllers of the components the same composite configuration is used:

@Composite(name = "searchComposite", compositeController = SearchComposite.class, selector = "searchId")

**Comment by FrankHossfeld** [comment]
Which one of both compocite is cached?

**Comment by TDesjardins** [comment]
> Which one of both composites is cached?

There is only one composite and it looks like that the caching works but when returning to the component, that was shown first with this composite, the composite on this component is removed. The composite is then only visible on the page that has last shown **initially** the composite.

**Comment by FrankHossfeld** [comment]
Thanks for clearifing. Will look at it during the next days and come back to you.

**Comment by FrankHossfeld** [comment]
Handling of stored composites have been improved. Please check, if it will fix the issue.
Thanks!

**Comment by TDesjardins** [comment]
Caching of composites works for 1.3.2-Snaphot for one page when a page is reloaded. The status of a composite kept when reloading the page. But if you place the same composite on different pages every composite of every page has it's own status. The origin request was about to keep the same status on all sites the composite is placed on (a kind of singleton). Because both e.g. all scenarios make sense the behaviour could be controlled by a parameter on method `storeInCache`.

**Comment by FrankHossfeld** [comment]
Yeah, in v1.3.1 is a bug regarding the caching of composite in one component. So, I thought, this issue relates to this bug and fixed it. (your test case showed, that it worked) but that is not what sou expected. 

I have created a new issue (#72) to discuss the implementation of your request.

**Comment by TDesjardins** [comment]
Ok, works as expected non global. Thanks!
