### ISSUE TITLE
Add a new method onLoaded to the Controller

### ISSUE THREAD

**Issue by schube** [NaluKit/nalu#68]
Can you please add a method called onLoaded maybe, which is called AFTER the component was added to the DOM.

Background: I have to add a 3rd party app which is looking for DIV with a certain ID to render some stuff.

Thank you

**Comment by FrankHossfeld** [comment]
HI, just checked the `start`-method of a `AbstractComponentController`. The component is attached to the DOM and I am able to search for a div with id ‚myId‘ and to append another element.

Is there something special (caching, etc.)?

Can you provide the PayPal-Button code?

**Comment by schube** [comment]
Hi!

You are right, **sorry**. Turns out, it was a typo when looking for the DIV...
