### ISSUE TITLE
Allow creation of "Items"

### ISSUE THREAD

**Issue by schube** [NaluKit/nalu#69]
It would be grate, if Nalu allowed the creation of "Items" (Sorry, I do not have a better name).

It would be something like a Composite, so a sub-unit/item with context/eventbus (maybe without router). But I want to create multiple of these items with code, and not like a composite with an annotation.

Think about it like a "BasketComponent" which has several "BasketItems" with their one logic like changing the quantity, removing etc.

**Comment by FrankHossfeld** [comment]
possible duplicate? see #65

**Comment by schube** [comment]
yes, sorry
