### ISSUE TITLE
Unused generated code is causing compiler warnings

### ISSUE THREAD

**Issue by eguardiola** [NaluKit/nalu#84]
The problem is present on the generated code for the  method setParameter for an ControllerCreator:
```java
@Override
  public void setParameter(Object object, String... parms) throws RoutingInterceptionException {
    PersonnelController controller = (PersonnelController) object;
    StringBuilder sb01 = new StringBuilder();
  }
```

The controller and sb01 will not be used so don't need to be generated. This will cause the java compiler not emit a warning.

**Comment by FrankHossfeld** [comment]
Done
