### ISSUE TITLE
Routing backward has more steps than forward

### ISSUE THREAD

**Issue by TDesjardins** [NaluKit/nalu#85]
If you start your Nalu app and navigate three times and then use the browsers back button to navigate back you can push it four times. So there is magically one history entry more than expected. Presumably it has something to do with the start route.

**Comment by TDesjardins** [comment]
If you go back to (1) using the back-button which URL do you expect?

**Comment by FrankHossfeld** [comment]
You will get www.myurl.com and this url will be processed by Nalu. In this case Nalu recognized an initial load and will use the start route. So, the user will see the content of (2).

**Comment by TDesjardins** [comment]
> You will get [www.myurl.com](http://www.myurl.com) and this url will be processed by Nalu. In this case Nalu recognized an initial load and will use the start route. So, the user will see the content of (2).

Should that also happen if the initial URL already represents the start route?

**Comment by FrankHossfeld** [comment]
Thas will only happens in case the initial url has no route.
