### ISSUE TITLE
Add html metatag manipulation support for page navigation

### ISSUE THREAD

**Issue by TDesjardins** [NaluKit/nalu#90]
Would be nice to have the possibility to add/set html metatags for the different pages. The idea is to provide a method in the controllers that could be overriden by need and delivers a map of metatags that would be set when navigating to the page/view.

**Comment by FrankHossfeld** [comment]
A possible implementation might look like that:

1. we need a model to store the informations.

2. we add an instance variable to the `AbstractComponentController`-class. In case it's null, Nalu will ingnore it. So, in case the developer sets the variable, Nalu will use it. The user can create the model somewhere inside the `start()`- or `activate()`-method.

3. at the end of a routing, Nalu will use the last value (in case that there are more than one) of the instance variable.

4. to handle the data, we create a factory that will store the data. In case the data is alerady is set, the old values will be used to remove the last tags, adds the new tags and store the data locally for removing the next time.

5. the plugins need a new method to do the update. 

What do you think?

**Comment by FrankHossfeld** [comment]
Done
