### ISSUE TITLE
Update Elemental2: v1.0.0-RC1 to v1.0.0

### ISSUE THREAD

**Issue by factuno-db** [NaluKit/nalu#94]
Blocking: release of GWT2.9

**Comment by FrankHossfeld** [comment]
Use the most updated version of Elemental2: v1.1.0

**Comment by FrankHossfeld** [comment]
Moving to Elemental2 v1.1.0 requires GWT 2.9.0 or newer.  This will exclude everybody who is using GWT 2.8.2 from the latest Nalu release. Think we need two releases. One for GWT 2.8.2 and one for GWT 2.9.0.

**Comment by FrankHossfeld** [comment]
This issue faces the same problem like #128.

I close this issue. Any comment related to that issue, please add to #128.
