### ISSUE TITLE
ErrorProne check: CollectionIncompatibleType in AbstractRouter

### ISSUE THREAD

**Issue by factuno-db** [NaluKit/nalu#95]
When running Nalu-Processor v1.3.2, I'm getting the following ErrorProne error:
`/com/github/nalukit/nalu/client/internal/route/AbstractRouter.java:793: error: [CollectionIncompatibleType] Argument 'c' should not be passed to this method; its type AbstractComponentController<?, ?, ?> is not compatible with its collection's type argument String controllerList.forEach(c -> this.activeComponents.remove(c)); ^ (see https://errorprone.info/bugpattern/CollectionIncompatibleType)`

**Comment by FrankHossfeld** [comment]
Fixed
